# Generated by Django 2.0.6 on 2018-06-22 16:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kenya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_area', models.FloatField()),
                ('unit_perim', models.FloatField()),
                ('district', models.CharField(max_length=50)),
                ('count', models.FloatField()),
                ('county_nam', models.CharField(max_length=50)),
                ('code', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
